# Generated by Django 3.2.5 on 2021-12-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.TimeField(blank=True)),
                ('body', models.TextField()),
                ('card_image', models.TextField()),
                ('has_images', models.BooleanField()),
            ],
        ),
    ]
