# Generated by Django 3.2.5 on 2021-12-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_articles_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='has_images',
        ),
        migrations.AlterField(
            model_name='articles',
            name='card_image',
            field=models.TextField(default='https://www.crictracker.com/wp-content/uploads/2018/10/PCB.jpg'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date_of_creation',
            field=models.CharField(default='DD/MM/YY', max_length=50),
        ),
    ]
