# Generated by Django 3.2.5 on 2021-12-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_delete_articlewithimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img1',
            field=models.TextField(blank=True, default='https://www.crictracker.com/wp-content/uploads/2018/10/PCB.jpg'),
        ),
        migrations.AddField(
            model_name='articles',
            name='img2',
            field=models.TextField(blank=True, default='https://www.crictracker.com/wp-content/uploads/2018/10/PCB.jpg'),
        ),
        migrations.AddField(
            model_name='articles',
            name='img3',
            field=models.TextField(blank=True, default='https://www.crictracker.com/wp-content/uploads/2018/10/PCB.jpg'),
        ),
    ]
