# Generated by Django 3.2.5 on 2021-12-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20211213_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='body',
            new_name='para1',
        ),
        migrations.AddField(
            model_name='articles',
            name='para2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='para3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='para4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='para5',
            field=models.TextField(blank=True),
        ),
    ]
