# Generated by Django 3.2.5 on 2021-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_players_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
