# Generated by Django 3.2.5 on 2021-11-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_players_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='positon',
        ),
        migrations.RemoveField(
            model_name='players',
            name='ranking',
        ),
        migrations.AddField(
            model_name='players',
            name='bio',
            field=models.TextField(default='.'),
        ),
        migrations.AddField(
            model_name='players',
            name='date_of_birth',
            field=models.DateField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='players',
            name='height',
            field=models.DecimalField(decimal_places=4, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
