# Generated by Django 3.2.5 on 2021-11-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20211121_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='T20Players',
        ),
    ]
