# Generated by Django 3.2.5 on 2021-11-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20211201_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODIPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField(default='2001-01-01')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ranking', models.CharField(default='N/A', max_length=10)),
                ('role', models.CharField(choices=[('Right Handed Batter', 'Right Handed Batter'), ('Left Handed Batter', 'Left Handed Batter'), ('All-Rounder', 'All-Rounder'), ('Right Arm Fast Bowler', 'Right Arm Fast Bowler'), ('Left Arm Fast Bowler', 'Left Arm Fast Bowler'), ('Right Arm Off Spinner', 'Right Arm Off Spinner'), ('Left Arm Off Spinner', 'Left Arm Off Spinner'), ('Leg Spinner', 'Leg Spinner')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.TextField()),
                ('bio', models.TextField(default='.')),
            ],
        ),
    ]
