# Generated by Django 3.2.5 on 2021-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_testplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t20players',
            name='title',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
